project_name: coingecko-api
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Bikram Dhoju <bikram.dhoju@gmail.com>
  description: coingecko-api
  homepage: https://github.com/becram
  license: MIT
  formats:
  - deb
  - rpm
  - apk
